source 'https://github.com/CocoaPods/Specs.git'

platform :ios, "8.0"

target 'JCCollectionViewWaterfallLayout_Example' do
  pod "JCCollectionViewWaterfallLayout", :path => "../"
  pod "AFNetworking", "3.0.4"
end

target 'JCCollectionViewWaterfallLayout_Tests'  do
  pod "JCCollectionViewWaterfallLayout", :path => "../"
end
