source 'https://github.com/CocoaPods/Specs.git'

target 'JCCollectionViewWaterfallLayout_Example', :exclusive => true do
  pod "JCCollectionViewWaterfallLayout", :path => "../"
  pod "AFNetworking", "3.0.4"
end

target 'JCCollectionViewWaterfallLayout_Tests', :exclusive => true do
  pod "JCCollectionViewWaterfallLayout", :path => "../"
end
